name: Install Certficicate
description: 'TODO'
inputs:
  p12-base64:
    description: 'The certificates in a PKCS12 file encoded as a base64 string.'
    required: true
  p12-password:
    description: 'The password used to import the PKCS12 file.'
    required: true
runs:
  using: 'node12'
  main: 'dist/main.js'
  post: 'dist/clean.js'
